is_import_model: False
import_model_name: '/model_state_10.pth'

mask_ratio: 0.25
pretrained: True
lr: 0.001
weight_decay: 0.05

epochs: 10

train_size: 1000
batch_size: 16
num_workers: 16

data_path: './data'
model_save_path: './model'
result_save_path: './result'