mask_ratio: 0.25
pretrained: True
lr: 0.0001
weight_decay: 0.05

epochs: 10

train_size: -6000
batch_size: 16
num_workers: 24

data_path: './data'
model_save_path: './model'
result_save_path: './result'

is_import_model: True
import_model_name: 